# Instrucciones para el Quiz 6

Estimado estudiante, reciba un cordial saludo.

Esta plataforma se conoce como un **cuaderno (_notebook_) de Jupyter**. La versión de Google se llamama **Colaboratory** o **Colab**. Actualmente este tipo de cuadernos son utilizados para los desarrollos en _machine learning_.

Estos cuadernos estan dividicos en **celdas**, cada celda puede ser de texto (en formato **markdown** y **latex**) o de código (en lenguaje **Python**)

Cuando usted inicia sesión con una cuenta de gmail (como la de la universidad) tiene acceso a estos cuadernos, los cuales se guardan en la carpeta Colab Notebooks de su cuenta de Google Drive.

El quiz 6 consiste en:
* Copiar este cuaderno en su cuenta de google drive (lo cual se hace iniciando sesión y en el menú seleccionar: Archivo->Guardar una copia en Drive)
* Editar este cuaderno con los datos solicitados
* Cada dos horas sacar una copia y __compartir el enlace__ con el profesor al enlace habilitado en el aula virtual (si tiene algún problema puede escribirme al correo: gmunoz@udistrital.edu.co ). 
  * Si termina antes de las primeras dos horas, sólo es necesario compartir el enlace final.
  * Pácticamente no hay límite de tiempo (realmente no puede pasar del lunes a las 11:59 pm), siempre y cuando envíe un enlace cada dos horas.
  * Si debe interrupir por alguna otra materia (y por lo tanto no puede enviar el enlace cada dos horas), entonces en la siguiete copia que enlace, indica la hora en que pudo retomar.  
  * Sugiero comenzar con los puntos del 6 al 10 y cuando tenga práctica hacer los puntos del 1 al 5.
  * No ovide colocar su nombre, código y grupo (Gr1 8am, Gr7 10am).
  * La nota sólo depende del enlace final, los otros enlaces son para conocer un poco sobre el avance individual. No hay que tomar fotos ni pantallazos. 
  * Despues de filalizar el quiz y si quierer conocer un poco más sobre python lo invito a iniciar sesión en kaggle.com y comenzar con los cursos de Python.

# Datos solicitados
Sabiendo que **$a$ es el último dígito** de su código y que **$b$ es el penúltimo dígito** de su código, debe editar este cuaderno cambiando las siguietes matrices:

* $  B_1=\left[\matrix{a&b+2 \\ a+1&b \\ a+2&b+5} \right]$

* $\vec{w}=\left(\matrix{2a+b+2 \\ 2a+b+2 \\ 2a+b+9} \right)$

* $  A_6=\left[\matrix{
a&0&0&4&5 \\ 
0&a&0&2&3 \\
0&0&b&6&1 \\ 
0&0&0&a+1&0 \\ 
0&0&0&0&b-1 \\ } \right]$ 

Si su $A_6$ no es diagonalizable no hay que encontrar ni $B_6$ ni $D_6$.







# Ejercicios de coordenadas y cambios de bases



Sea la matriz $  B_1=\left[\matrix{1&0 \\ 2&2 \\ 0&1} \right]$, cuyas columnas son base del subespacio $S=co(B1)$.

1. Usando Gram-Schmidt en la base $B_1$ encuentre la base ortogonal $B_2$.

2. Normalizando la base $B_2$ encuentre la base ortonormal $B_3$.

3. Encuentre la matriz $A_3$ para pasar de la base $B_1$  a la base $B_3$.

4. Encuentre la matriz $A_4$ para pasar de la base $B_3$ a la base $B_1$.

5. Encuentre las coordenadas de 

$\vec{w}=\left(\matrix{3 \\ 4 \\ -1} \right)$

en las bases:

  a. $B_1$

  b. $B_2$

  c. $B_3$

  d. $B_4$



# Solución de los ejercicios de coordenadas y cambios de bases:
Si $B_1=[\matrix{ v_1 & v_2 }]$ entonces: 
* $\vec{v}_1=\left(\matrix{1 \\ 2 \\ 0} \right)$
* $\vec{v}_2=\left(\matrix{0 \\ 2 \\ 1} \right)$

1. Usando el algoritmo de Gram-Schmidt obtenemos

* $\vec{u}_1=\vec{v}_1=\left(\matrix{1 \\ 2 \\ 0} \right)$

* $\vec{u}_2=\vec{v}_2-\frac{\vec{v}_2 \cdot \vec{u}_1}{\vec{u}_1 \cdot \vec{u}_1}=\left(\matrix{0 \\ 2 \\ 1} \right)-\frac{\left(\matrix{0 \\ 2 \\ 1} \right) \cdot \left(\matrix{1 \\ 2 \\ 0} \right)}{\left(\matrix{1 \\ 2 \\ 0} \right) \cdot \left(\matrix{1 \\ 2 \\ 0} \right)}\left(\matrix{1 \\ 2 \\ 0} \right)=\left(\matrix{0 \\ 2 \\ 1} \right)-\frac{4}{5}\left(\matrix{1 \\ 2 \\ 0} \right)=\left(\matrix{-\frac{4}{5} \\ \frac{2}{5} \\ 1} \right)$

$B_2=[\matrix{ u_1 & u_2 }]=\left[\matrix{ \matrix{1 \\ 2 \\ 0} & \matrix{-\frac{4}{5} \\ \frac{2}{5} \\ 1} }\right]$




2. Nomalizando cada vector obtenemios:
* $\hat{u}_1=\frac{1}{|\vec{u}_1|}\vec{u}_1=\frac{1}{\sqrt{5}}\left(\matrix{1 \\ 2 \\ 0} \right)=\left(\matrix{\frac{1}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} \\ 0} \right)$
* $\hat{u}_2=\frac{1}{|\vec{u}_2|}\vec{u}_2=\frac{\sqrt{5}}{3}\left(\matrix{-\frac{4}{5} \\ \frac{2}{5} \\ 1} \right)=\left(\matrix{\frac{-4\sqrt{5}}{15} \\ \frac{2\sqrt{5}}{15} \\ \frac{\sqrt{5}}{3}} \right)$

$B3=\left[\matrix{
  \matrix{\frac{1}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} \\ 0} 
  &
  \matrix{\frac{-4\sqrt{5}}{15} \\ \frac{2\sqrt{5}}{15} \\ \frac{\sqrt{5}}{3}} 
}\right]$






3. Para encontrar la matriz $A_3$ que pasa de la base $B_1=[\matrix{ \vec{v}_1 & \vec{v}_2 }]$ a la base $B_3=[\matrix{ \hat{u}_1 & \hat{u}_2 }]$ usamos la fórmula

$A_3=\left[\matrix{ [\vec{v}_1]_{B3} & [\vec{v}_2]_{B3}}\right]$. 

Las columnas de $A_3$ son las coordenadas de los vectores $\vec{v}_1$ y $\vec{v}_2$ en la base $B_3$. Para hallar estas coordenadas aprovechamos el hecho que $B_3$ es una base ortonormal.

$[\vec{v}_1]_{B3}=\left(\matrix{c_1 \\ c_2 }\right)$ 
$=\left(\matrix{\vec{v}_1 \cdot \hat{u}_1 \\ \vec{v}_1 \cdot \hat{u}_2 }\right) $ 
$=\left(\matrix{\left(\matrix{1 \\ 2 \\ 0} \right) 
\cdot \left(\matrix{\frac{1}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} \\ 0} \right)
\\ \left(\matrix{1 \\ 2 \\ 0} \right) 
\cdot \left(\matrix{\frac{-4\sqrt{5}}{15}  
\\ \frac{2\sqrt{5}}{15} \\ \frac{\sqrt{5}}{3}} \right)}\right)$ 
$=\left(\matrix{\sqrt{5} \\ 0}\right)$

$[\vec{v}_2]_{B3}=\left(\matrix{d_1 \\ d_2 }\right)$ 
$=\left(\matrix{\vec{v}_2 \cdot \hat{u}_1 \\ \vec{v}_2 \cdot \hat{u}_2 }\right) $ 
$=\left(\matrix{\left(\matrix{0 \\ 2 \\ 1} \right) 
\cdot \left(\matrix{\frac{1}{\sqrt{5}} \\ \frac{2}{\sqrt{5}} \\ 0} \right)
\\ \left(\matrix{0 \\ 2 \\ 1} \right) 
\cdot \left(\matrix{\frac{-4\sqrt{5}}{15}  
\\ \frac{2\sqrt{5}}{15} \\ \frac{\sqrt{5}}{3}} \right)}\right)$ 
$=\left(\matrix{\frac{4}{\sqrt{5}} \\ \frac{3}{\sqrt{5}}}\right)$

Por lo tanto:

$A_3=\left[\matrix{\matrix{\sqrt{5} \\ 0} & \matrix{\frac{4}{\sqrt{5}} \\ \frac{3}{\sqrt{5}}}}\right]$

4. Para pasar de la base $B_3$ a la base $B_1$ es la inversa de $A_3$

$A_4=A_3^{-1}=\frac{1}{3}\left[\matrix{\matrix{ \frac{3}{\sqrt{5}} \\ 0} & \matrix{-\frac{4}{\sqrt{5}} \\ \sqrt{5} }}\right]$

# Verificación


Primeo se definen las librerías a usar

In [0]:
import numpy as np # Librería de python para arreglos y matrices
import math # Librería para usar raiz cuadrada (sqrt)

`np.array( v )` permite definir vectores o matrices

In [0]:
u2=np.array([-4*math.sqrt(5)/15,2*math.sqrt(5)/15,math.sqrt(5)/3])
u2

array([-0.59628479,  0.2981424 ,  0.74535599])

Para realizar el producto punto se usa `np.dot`.

In [0]:
np.dot(u2,u2)

1.0

Lo anterior muestra que el vector $u_2$ es un vector unitario, como se esperaba.

A continuación se definen las matrices $B_3$ y $A_3$.

In [0]:
B3=np.array([[1/math.sqrt(5),-4*math.sqrt(5)/15],[2/math.sqrt(5),2*math.sqrt(5)/15],[0,math.sqrt(5)/3]])
B3

array([[ 0.4472136 , -0.59628479],
       [ 0.89442719,  0.2981424 ],
       [ 0.        ,  0.74535599]])

In [0]:
A3=np.array([[math.sqrt(5),4/math.sqrt(5)],[0,3/math.sqrt(5)]])
A3

array([[2.23606798, 1.78885438],
       [0.        , 1.34164079]])

Recordemos que 
```
         $R^3$
         /\
  $B_1$ /  \$B_3$
       /    \
  $R^2$ ----- $R^2$
        $A3$
``` 
(el signo $ hace referencia a texto con formato latex)


Ahora se va a probar que $B_1 = B_3 A_3$. Para la multiplicación de las matrices `B3 y `A_3` se utiliza `np.dot(B3,A3)`


In [0]:
np.dot(B3,A3)

array([[ 1.00000000e+00, -1.07940985e-16],
       [ 2.00000000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00]])

Observe que los cálculos numéricos dan una diferencia muy pequeña. Recuerde que en Python `-1.07e-16` equivale a $-1.07(10^{-16})=-0.000000000000000107$  


  
# Ejercicios de vectores y valores propios

6. Sea la matriz $  A_6=\left[\matrix{
5&0&0&4&5 \\ 
0&5&0&2&3 \\
0&0&5&6&1 \\ 
0&0&0&4&0 \\ 
0&0&0&0&4 \\ } \right]$. Encuentre sus valores propios  y para cada uno encuentre:

7. Las multiplicidades algebraicas (M.A.)

8. Las multiplicidades geométricas (M.G.)

9. Bases del espacio característico (vectores propios) 

10. Si es posible encontrar una base de $\mathbb{R}^5$ de vectores propios de $A_6$ entonces escribir la matriz $B_6$ que diagonaliza y la matriz diagonalizada $D_6$, tal que $A_6=B_6 D_6 B_6^{-1}$

# Solución de los ejercicios de vectores y valores propios:

6. y 7.  Recordemos que los valores propios son las raíces del polinomio característico dado por $det(A_6 - \lambda I)=0$. y los exponentes son las M.A.

En este caso, como la matriz característica $A_6 - \lambda I$ es un a matriz triangular entonces su determinante es la multiplicación de la diagonal. 

$  \left|\matrix{
5-\lambda&0&0&4&5 \\ 
0&5-\lambda&0&2&3 \\
0&0&5-\lambda&6&1 \\ 
0&0&0&4-\lambda&0 \\ 
0&0&0&0&4-\lambda \\ } \right|=(5-\lambda)^3(4-\lambda)^2=0$

$\lambda_1=5$ con M.A. 3

$\lambda_2=4$ con M.A. 2

9.

Ahora para cada valor propio hay que hallar su espacio característico, que es el espacio nulo de la matriz característica. Es decir, la solución del sistema homogéneo $[A_6 - \lambda_i I:0]$. 

Para $\lambda_1=5$

$\left[\matrix{
0&0&0&4&5&:&0 \\ 
0&0&0&2&3&:&0 \\
0&0&0&6&1&:&0 \\ 
0&0&0&-1&0&:&0 \\ 
0&0&0&0&-1&:&0 \\ } \right]$

Después de intercambiar algunos renglones se obtiene:

$\left[\matrix{
0&0&0&-1&0&:&0 \\ 
0&0&0&0&-1&:&0 \\ 
0&0&0&4&5&:&0 \\ 
0&0&0&2&3&:&0 \\
0&0&0&6&1&:&0 \\ 
} \right]$

Luego de multiplicar un par de renglones por -1 queda:

$\left[\matrix{
0&0&0&1&0&:&0 \\ 
0&0&0&0&1&:&0 \\ 
0&0&0&4&5&:&0 \\ 
0&0&0&2&3&:&0 \\
0&0&0&6&1&:&0 \\ 
} \right]$

Eliminando, finalmente queda la forma escalón:

$\left[\matrix{
0&0&0&1&0&:&0 \\ 
0&0&0&0&1&:&0 \\ 
0&0&0&0&0&:&0 \\ 
0&0&0&0&0&:&0 \\ 
0&0&0&0&0&:&0 \\ 
} \right]$

Las primeras tres variables son libres y por lo tanto se le asignan parámetros

$x_1=t_1$

$x_2=t_2$

$x_3=t_3$

Las otras dos variables como son delanteras de pueden despejar de las dos primeras ecuaciones.

$x_4=0$

$x_5=0$

De esta forma escribimos la solución general

$\left(\matrix{x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ } \right)=t_1\left(\matrix{1 \\ 0 \\ 0 \\ 0 \\ 0 \\ } \right)+t_2\left(\matrix{0 \\ 1 \\ 0 \\ 0 \\ 0 \\ } \right)+t_3\left(\matrix{0 \\ 0 \\ 1 \\ 0 \\ 0 \\ } \right)$

Por lo tanto, la base del primer espacio característico es


$\left\{\left(\matrix{1 \\ 0 \\ 0 \\ 0 \\ 0 \\ } \right),\left(\matrix{0 \\ 1 \\ 0 \\ 0 \\ 0 \\ } \right),\left(\matrix{0 \\ 0 \\ 1 \\ 0 \\ 0 \\ } \right) \right\}$


Para $\lambda_2=4$

$\left[\matrix{
01&0&0&4&5&:&0 \\ 
0&1&0&2&3&:&0 \\
0&0&1&6&1&:&0 \\ 
0&0&0&0&0&:&0 \\ 
0&0&0&0&0&:&0 \\ } \right]$


Las últimas dos variables son libres y por lo tanto se le asignan parámetros

$x_4=t_1$

$x_5=t_2$


Las otras tres variables como son delanteras de pueden despejar de las tres primeras ecuaciones.

$x_1=-4t_1-5t_2$

$x_2=-2t_1-3t_2$

$x_3=-6t_1-1t_2$

De esta forma escribimos la solución general

$\left(\matrix{x_1 \\ x_2 \\ x_3 \\ x_4 \\ x_5 \\ } \right)=t_1\left(\matrix{-4 \\ -2 \\ -6 \\ 1 \\ 0 \\ } \right)+t_2\left(\matrix{-5 \\ -3 \\ -1 \\ 0 \\ 1 \\ } \right) $

Por lo tanto, la base del segundo espacio característico es

$\left\{\left(\matrix{-4 \\ -2 \\ -6 \\ 1 \\ 0 \\ } \right),\left(\matrix{-5 \\ -3 \\ -1 \\ 0 \\ 1 \\ } \right) \right\} $

8. La M.G. corresponde con el número elementos de las bases de los espacios característicos. 

Para el primer $\lambda$ la M.G es 3 los que implica que el primer espacio característico es un espacio de 3D en $\mathbb{R}^5$.

Para el segundo $\lambda$ la M.G es 2 los que implica que el segundo espacio característico es un plano en $\mathbb{R}^5$.

10. Como cada M.A es igual a su respectiva M.G entonces la matriz $A_6$ si es diagonalizable. La base de vectores propios que diagonaliza la matriz es:

$B_6=\left[\matrix{1&0&0&-4&-5 \\0&1&0& -2&-3 \\ 0&0&1&-6&-1 \\ 0&0&0&1&0 \\ 0&0&0&0&1 \\ } \right]$

y la matriz diagonalizada es:

$D_6=\left[\matrix{ 5&0&0&0&0 \\ 0&5&0&0&0 \\ 0&0&5&0&0 \\ 0&0&0&4&0 \\ 0&0&0&0&4 \\ } \right]$


# Verificación usando python

A continuación se definen en Python las matrices $B_6$ y  $D_6$


In [0]:
import numpy as np # Librería de python para arreglos y matrices
B=np.array([[1,0,0,-4,-5],[0,1,0,-2,-3],[0,0,1,-6,-1],[0,0,0,1,0],[0,0,0,0,1]])
B

array([[ 1,  0,  0, -4, -5],
       [ 0,  1,  0, -2, -3],
       [ 0,  0,  1, -6, -1],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  1]])

In [0]:
D=np.array([[5,0,0,0,0],[0,5,0,0,0],[0,0,5,0,0],[0,0,0,4,0],[0,0,0,0,4]])
D

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

El siguiete paso es comprobar que $A_6=B_6 D_6 B_6^{-1}$

La librería `numpy` (o su alias `np`) permite realizar las siguietes instrucciones:
* Para la multiplicación de las matrices `B` y `D` se utiliza `np.dot(B,D)`.
* Para invertir la matriz `B` se utiliza `np.linalg.inv(B)`

A continuación se imprime el resultado de la operación $(B_6 D_6) B_6^{-1}$

In [0]:

np.dot(np.dot(B,D),np.linalg.inv(B))


array([[5., 0., 0., 4., 5.],
       [0., 5., 0., 2., 3.],
       [0., 0., 5., 6., 1.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

Finalmente, podemos comprobar que el resultado corresponde a la matriz $A_6$